# Generated by Django 3.2.4 on 2021-10-03 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('userid', models.EmailField(max_length=100)),
                ('status', models.BooleanField()),
                ('cdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=40)),
                ('bpic', models.ImageField(default='', upload_to='static/brand/')),
                ('bdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=120)),
                ('mobile', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('userid', models.EmailField(max_length=100)),
                ('remarks', models.CharField(max_length=40)),
                ('status', models.BooleanField()),
                ('odate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=10)),
                ('Dob', models.DateField()),
                ('Mobile', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=100)),
                ('Password', models.CharField(max_length=20)),
                ('Address', models.TextField(max_length=500)),
                ('Photo', models.ImageField(default='', upload_to='static/profile/')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=150)),
                ('ppic', models.ImageField(default='', upload_to='static/product/')),
                ('pcolor', models.CharField(max_length=12)),
                ('tprice', models.FloatField()),
                ('disprice', models.FloatField()),
                ('pdes', models.TextField(max_length=500)),
                ('pdate', models.DateField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.brand')),
            ],
        ),
    ]
