# Generated by Django 3.2.4 on 2021-10-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
